-- =============================================
-- DATOS DE PRUEBA - SaludAlerta
-- AlertasDB - Oracle Autonomous
-- Ejecutar en: Oracle Database Actions > SQL
-- =============================================

-- Secuencias (si no existen)
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE PACIENTE_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SENAL_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE ALERTA_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =============================================
-- 10 PACIENTES
-- =============================================
INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'María González López', '12.345.678-9', DATE '1975-03-15', 'Insuficiencia cardíaca congestiva', 'UCI-01');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Carlos Rodríguez Muñoz', '13.456.789-0', DATE '1960-07-22', 'Infarto agudo al miocardio', 'UCI-02');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Ana Martínez Soto', '15.678.901-2', DATE '1988-11-08', 'Neumonía bacteriana severa', 'INT-01');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Pedro Fuentes Araya', '10.234.567-8', DATE '1950-01-30', 'Accidente cerebrovascular', 'NEU-01');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Lucía Herrera Vega', '16.789.012-3', DATE '1995-05-14', 'Sepsis severa', 'UCI-03');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Roberto Silva Castro', '11.345.678-K', DATE '1968-09-03', 'Insuficiencia renal aguda', 'INT-02');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Valentina Torres Díaz', '17.890.123-4', DATE '2001-12-20', 'Politraumatismo por accidente', 'UCI-04');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Jorge Morales Pérez', '9.456.789-1', DATE '1945-06-18', 'EPOC reagudizada', 'RES-01');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Carmen López Núñez', '14.567.890-2', DATE '1982-04-25', 'Preeclampsia severa', 'OBS-01');

INSERT INTO PACIENTES (ID, NOMBRE, RUT, FECHA_NACIMIENTO, DIAGNOSTICO, CAMA)
VALUES (PACIENTE_SEQ.NEXTVAL, 'Francisco Castillo Reyes', '18.901.234-5', DATE '1990-08-11', 'Cetoacidosis diabética', 'INT-03');

-- =============================================
-- SEÑALES VITALES (2 por paciente)
-- =============================================
-- Paciente 1 - UCI-01 (valores críticos)
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 1, 118, 95, 60, 88.5, 38.7, 28, SYSTIMESTAMP - INTERVAL '2' HOUR);

INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 1, 110, 98, 62, 90.0, 38.5, 26, SYSTIMESTAMP - INTERVAL '1' HOUR);

-- Paciente 2 - UCI-02 (post infarto)
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 2, 95, 140, 90, 93.0, 37.2, 20, SYSTIMESTAMP - INTERVAL '3' HOUR);

INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 2, 88, 135, 85, 94.5, 37.0, 18, SYSTIMESTAMP - INTERVAL '1' HOUR);

-- Paciente 3 - INT-01
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 3, 102, 120, 78, 91.0, 39.1, 24, SYSTIMESTAMP - INTERVAL '4' HOUR);

INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 3, 98, 118, 76, 92.5, 38.9, 22, SYSTIMESTAMP - INTERVAL '2' HOUR);

-- Paciente 4 - NEU-01
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 4, 72, 160, 100, 95.0, 37.5, 18, SYSTIMESTAMP - INTERVAL '5' HOUR);

INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 4, 70, 155, 98, 96.0, 37.3, 17, SYSTIMESTAMP - INTERVAL '2' HOUR);

-- Paciente 5 - UCI-03 (sepsis - crítico)
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 5, 125, 85, 50, 86.0, 40.2, 32, SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 5, 130, 82, 48, 85.0, 40.5, 34, SYSTIMESTAMP);

-- Paciente 6 - INT-02
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 6, 80, 148, 92, 96.0, 37.8, 19, SYSTIMESTAMP - INTERVAL '3' HOUR);

INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 6, 82, 145, 90, 95.5, 37.6, 18, SYSTIMESTAMP - INTERVAL '1' HOUR);

-- Paciente 7 - UCI-04
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 7, 108, 100, 65, 92.0, 37.9, 25, SYSTIMESTAMP - INTERVAL '2' HOUR);

-- Paciente 8 - RES-01
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 8, 88, 130, 82, 89.0, 37.1, 26, SYSTIMESTAMP - INTERVAL '4' HOUR);

-- Paciente 9 - OBS-01
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 9, 92, 158, 105, 97.0, 37.4, 20, SYSTIMESTAMP - INTERVAL '1' HOUR);

-- Paciente 10 - INT-03
INSERT INTO SENALES_VITALES (ID, PACIENTE_ID, FRECUENCIA_CARDIACA, PRESION_SISTOLICA, PRESION_DIASTOLICA, SATURACION_OXIGENO, TEMPERATURA, FRECUENCIA_RESPIRATORIA, FECHA_REGISTRO)
VALUES (SENAL_SEQ.NEXTVAL, 10, 105, 125, 80, 93.5, 38.3, 22, SYSTIMESTAMP - INTERVAL '2' HOUR);

-- =============================================
-- ALERTAS
-- =============================================
INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 1, 'Hipoxemia crítica', 'Saturación O2 88.5% - Muy por debajo del umbral mínimo (95%). Requiere oxigenoterapia inmediata.', 'CRITICO', 0, SYSTIMESTAMP - INTERVAL '2' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 1, 'Taquicardia', 'Frecuencia cardíaca 118 bpm. Paciente con insuficiencia cardíaca en descompensación.', 'ALTO', 0, SYSTIMESTAMP - INTERVAL '2' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 2, 'Hipertensión', 'Presión arterial 140/90 mmHg en paciente post infarto. Monitoreo continuo requerido.', 'ALTO', 1, SYSTIMESTAMP - INTERVAL '3' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 3, 'Fiebre alta', 'Temperatura 39.1°C en paciente con neumonía bacteriana. Cultivos pendientes.', 'MEDIO', 0, SYSTIMESTAMP - INTERVAL '4' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 4, 'Hipertensión severa', 'PA 160/100 mmHg en paciente con ACV. Riesgo de sangrado cerebral.', 'CRITICO', 0, SYSTIMESTAMP - INTERVAL '5' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 5, 'Shock séptico', 'PA 85/50 mmHg con FC 125 bpm y temperatura 40.2°C. Sepsis en progresión.', 'CRITICO', 0, SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 5, 'Hipoxemia', 'SpO2 86% con taquipnea de 34 rpm. Considerar ventilación mecánica.', 'CRITICO', 0, SYSTIMESTAMP);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 7, 'Taquicardia moderada', 'FC 108 bpm en politraumatizado. Descartar hemorragia interna.', 'ALTO', 0, SYSTIMESTAMP - INTERVAL '2' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 8, 'Hipoxemia moderada', 'SpO2 89% en paciente con EPOC. Ajustar FiO2.', 'MEDIO', 1, SYSTIMESTAMP - INTERVAL '4' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 9, 'Preeclampsia severa', 'PA 158/105 mmHg en embarazada. Riesgo de eclampsia. Notificar equipo obstétrico.', 'CRITICO', 0, SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO ALERTAS (ID, PACIENTE_ID, TIPO_ALERTA, DESCRIPCION, NIVEL, ATENDIDA, FECHA_ALERTA)
VALUES (ALERTA_SEQ.NEXTVAL, 10, 'Taquicardia', 'FC 105 bpm en cetoacidosis. Verificar glucemia y electrolitos.', 'MEDIO', 0, SYSTIMESTAMP - INTERVAL '2' HOUR);

COMMIT;

-- Verificar datos insertados
SELECT 'PACIENTES: ' || COUNT(*) AS resumen FROM PACIENTES
UNION ALL
SELECT 'SENALES: '  || COUNT(*) FROM SENALES_VITALES
UNION ALL
SELECT 'ALERTAS: '  || COUNT(*) FROM ALERTAS;
